config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get '/gift/new/:event_name', to: 'main#gift_new', as: :gift_new_event
  get '/gift/rank', to: 'main#gift_rank'
  get '/gift/recommend', to: 'main#gift_recommend'
  
  get '/index/:event_name', to: 'main#index', as: :index_event
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    month = Date.today.strftime("%m").to_i.to_s
    next_month = (month.to_i+1).to_s
    birthmonth = "( " + month + "・" + next_month + " 月 )"
    
    en2ja = { "birthday" => "誕生日#{birthmonth}",
              "coming_of_age" => "成人の日",
              "valentine" => "バレンタインデー",
              "white" => "ホワイトデー",
              "graduation" => "卒業式・追いコン",
              "entrance" => "入学式",
              "childrens" => "こどもの日",
              "mothers" => "母の日",
              "fathers" => "父の日",
              "thanksgiving" => "敬老感謝の日",
              "halloween" => "ハロウィン",
              "christmas" => "クリスマス"}
    if params[:event_name]==nil then
      @event_name_en = date2event(Date.today.strftime("%m%d"))
      @event_name_ja = en2ja[date2event(Date.today.strftime("%m%d"))]
    else
      @event_name_en = params[:event_name]
      @event_name_ja = en2ja[params[:event_name]]
    end
  end

  def gift_new
    event_name = params[:event_name]
    raw_hashes = []
    for month in month_from_event_name(event_name)
      year = month_to_year(month)
      filename = "#{Rails.root}/lib/new_release/new_release_#{year}_#{month}.json"
      raw_hashes.push(get_json(filename))
    end
    
    result = convert_with_price(raw_hashes)
    @petitprice, @lowprice, @middleprice, @highprice = *result
    
    month = Date.today.strftime("%m").to_i.to_s
    next_month = (month.to_i+1).to_s
    birthmonth = "( " + month + "・" + next_month + " 月 )"
    
    en2ja = { "birthday" => "誕生日#{birthmonth}",
              "coming_of_age" => "成人の日",
              "valentine" => "バレンタインデー",
              "white" => "ホワイトデー",
              "graduation" => "卒業式・追いコン",
              "entrance" => "入学式",
              "childrens" => "こどもの日",
              "mothers" => "母の日",
              "fathers" => "父の日",
              "thanksgiving" => "敬老感謝の日",
              "halloween" => "ハロウィン",
              "christmas" => "クリスマス"}
    if params[:event_name]==nil then
      @event_name_en = date2event(Date.today.strftime("%m%d"))
      @event_name_ja = en2ja[date2event(Date.today.strftime("%m%d"))]
    else
      @event_name_en = params[:event_name]
      @event_name_ja = en2ja[params[:event_name]]
    end
  end

  def gift_rank
    params = URI.encode_www_form({
      count: 50,
      client_id: '8f58b3318661f361f8e9b132ac356867d25ff005b4205b20eb1ce7f191cc0ccd'
    })
    uri = URI.parse("https://pf-api.cosme.net/cosme/v2/ranking/products?#{params}")
    raw_hash = exec_api(uri)
    @ranking = convert_with_rank(raw_hash)
  end

  def gift_recommend
  end

  def gift_event
  end

  def gift_month
  end
end


def exec_api(uri)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(uri.request_uri)
    res = http.request(request)
    raw_hash = JSON.parse(res.body)
    return raw_hash
end

def get_json(filename)
  begin
    raw_hash = File.open(filename) do |json_file|
      JSON.load(json_file)
    end
  rescue => error
    filename = "#{Rails.root}/lib/new_release/sample.json"
    raw_hash = File.open(filename) do |json_file|
      JSON.load(json_file)
    end
  end
  return raw_hash
end

def convert_with_price(raw_hashes)
  group_by_price_range = [{}, {}, {}, {}]
  for raw_hash in raw_hashes
    for res_hash in raw_hash["results"]
      release_at, brands = res_hash["date"], res_hash["brands"]
      for brand in brands
        brand_name = brand["brand_name"]
        for group in group_by_price_range
          group[brand_name] = [] if !group.has_key?(brand_name)
        end
        for product in brand["products"]
          if product["sku"]["volume_sales"].length.zero?
            next
          end
          price = product["sku"]["volume_sales"][0]["sales"]["price_value_from"]
          if product["image_url"].nil?
            product["image_url"] = "https://lh3.googleusercontent.com/proxy/q9K-584jea7P1JJu_HKizXAOZRuGvhq3hqpTF_mMamAgF9vr8NBtWUgLeGnHUx0yPjZnR3sI26QeTbWfUlDynP6Y3oayozuRRdqKFY8"
          end
          prod = {
            "item_name" => product["product_name"],
            "price" => price,
            "image_url" => product["image_url"],
            "release_at" => Date.strptime(release_at,'%Y-%m-%d'),
            "shopping_link" => product["shopping_link"]
          }
          group_by_price_range[rate_index(price.to_i)][brand_name].push(prod)
        end
      end
    end
  end
  group_by_price_range.each_with_index{|group, index|
    new_group = []
    group.each{|brand_name, products|
      if products.length.zero?
        next
      end
      new_group.push({"brand_name"=>brand_name, "products" => products})
    }
    group_by_price_range[index] = new_group
  }
  return group_by_price_range
end

def rate_index(price)
  if price < 2000 then
    return 0
  elsif price < 5000
    return 1
  elsif price < 10000
    return 2
  else
    return 3
  end
end

def convert_with_rank(raw_hash)
  converted_rank = []
  for rank in raw_hash["result"]
    item = {
        'rank'=> rank['rank'],
        'item_name'=> rank['product_name'],
        'brand_name'=> rank['brand_name'],
        'volume_price_label'=> rank['volume_price_label'],
        'image_url'=> rank['image_url'],
        'shopping_link'=> rank['shopping_link']
    }
    converted_rank.append(item)
  end
  return converted_rank
end

# date:String (example: date = "0125")
def date2event(date)
  if date <= "0115" then
    return "coming_of_age"
  elsif date <= "0214" then
    return "valentine"
  elsif date <= "0314" then
    return "white"
  elsif date <= "0331" then
    return "graduation"
  elsif date <= "0415" then
    return "entrance"
  elsif date <= "0505" then
    return "childrens"
  elsif date <= "0515" then
    return "mothers"
  elsif date <= "0615" then
    return "fathers"
  elsif date <= "0921" then
    return "thanksgiving"
  elsif date <= "1031" then
    return "halloween"
  elsif date <= "1225" then
    return "christmas"
  elsif date <= "1231" then
    return "coming_of_age"
  else
    return false
  end
end

def month_from_event_name(event)
  if event == "coming_of_age" then
    return [12,1]
  elsif event == "valentine" then
    return [1,2]
  elsif event == "white" then
    return [2,3]
  elsif event == "graduation" then
    return [2,3]
  elsif event == "entrance" then
    return [3,4]
  elsif event == "childrens" then
    return [4,5]
  elsif event == "mothers" then
    return [4,5]
  elsif event == "fathers" then
    return [5,6]
  elsif event == "thanksgiving" then
    return [8,9]
  elsif event == "halloween" then
    return [9,10]
  elsif event == "christmas" then
    return [11,12]
  elsif event == "birthday" then
    month = Date.today.month
    return [month,month+1]
  end
end


def month_to_year(month)
  today = Date.today
  if today.month+1 < month
    return today.year - 1
  end
  return today.year
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_event.html.erb
<%  path = request.path
    path_length = path.length
    if path_length==1 then
      flg=0
    else
      if path[1..5]=="index" then
        flg=0
      else
        flg=1
      end
    end  %>
<%  month = Date.today.strftime("%m").to_i.to_s
    next_month = (month.to_i+1).to_s
    birthmonth = "( " + month + "・" + next_month + "月 )" %>
<% ja2en = {"誕生日#{birthmonth}" => "birthday",
            "成人の日" => "coming_of_age",
            "バレンタインデー" => "valentine",
            "ホワイトデー" => "white",
            "卒業式・追いコン" => "graduation",
            "入学式" => "entrance",
            "こどもの日" => "childrens",
            "母の日" => "mothers",
            "父の日" => "fathers",
            "敬老感謝の日" => "thanksgiving",
            "ハロウィン" => "halloween",
            "クリスマス" => "christmas"} %>
<% months = ["1月", "2月", "3月", "4月", "5月", "6月", 
             "7月", "8月", "9月", "10月", "11月", "12月"] %>

<div class="events col-md-2">
  <h4>イベント一覧</h4>
  <ul>
    <% ja2en.each do |key, value| %>
      <% if flg==0 then%>
        <a href=<%= index_event_path(value) %> ><li class="event <%= value %>"><%= key %></li></a>
      <% else %>
        <a href=<%= gift_new_event_path(value) %> ><li class="event <%= value %>"><%= key %></li></a>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<div class="links col-md-3">
  @cosme ホームページ：
  <a href="https://www.cosme.net" target="_blank"><%= image_tag("at_cosme_icon_circle.png", :size =>'40x40', alt: "@cosme icon") %></a>
</div>
<div class="links col-md-5">
  @cosme 公式SNSアカウント：
  <a href="https://twitter.com/atcosmenet" target="_blank"><%= image_tag("twitter_icon_circle.png", :size =>'40x40', alt: "twitter icon") %></a>
  <a href="https://www.facebook.com/atcosme/" target="_blank"><%= image_tag("fb_icon_circle.png", :size =>'40x40', alt: "facebook icon") %></a>
  <a href="https://line.me/R/ti/p/%40at_cosme" target="_blank"><%= image_tag("line_icon_circle.png", :size =>'40x40', alt: "line icon") %></a>
</div>
<div class="links col-md-4">
  @cosme宣言：
  <a href="https://www.cosme.net/html/sng/index.html" target="_blank"><%= image_tag("at_cosme_declaration.png", :size =>'130x40', alt: "@cosme declaration icon") %></a>
</div>
<div class="copyright col-md-12">
  copyright©istyle,inc.
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_title.html.erb
<div class="logo col-md-10">
  <a href=<%= root_path %>><%= image_tag("for_gift_logo.png", :size =>'420x61', alt: "@cosme logo") %></a>
</div>
<div class="page_links col-md-1">
  <ul id="dropmenu">
    <li><a href="#">メニュー</a>
      <ul>
        <li><a href=<%= root_path %>>▶︎トップページへ</a></li>
        <li><a href=<%= gift_new_event_path("birthday") %>>▶︎新作コスメへ</a></li>
        <li><a href=<%= gift_rank_path %>>▶︎週間ランキングへ</a></li>
        <li><a href=<%= gift_recommend_path %>>▶︎おすすめへ</a></li>
      </ul>
    </li>
  </ul>
</div>
<div class="icon col-md-1">
  <a href="https://www.cosme.net" target="_blank"><%= image_tag("at_cosme_icon.jpg", :size =>'66x61', alt: "@cosme icon") %></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'index', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </head>

  <body>
    <div class="container">
      <div class="title">
        <%= render 'layouts/title' %>
      </div>
      <div class="main row">
        <%= render 'layouts/event' %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
    <!--スタイルシートの次に埋め込んであったやつを以下に埋め込んで成功した-->
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/main/gift_new.html.erb
<%= stylesheet_link_tag 'gift' %>
<% provide(:title, "新作コスメ") %>

<div class="col-md-9" style="margin-top: 3rem" ;>
  <div class="price">
    <ul id="price-list">
      <h2><%= tag.span @event_name_ja, class:"under-lined #{@event_name_en+"_content"}" %><span style="font-size: 0.7em;">のプレゼントに</span></h2>
      <li class="price-list-item">
        <div class="list-head">
          <h3 class="list-name">プチプラ</h3>
          <span class="list-icon <%= @event_name_en+"_content" %>">+</span>
        </div>
        <div class="answer">
          <% @petitprice.each do |brand| %>
          <div class="row">
            <%= tag.span brand["brand_name"], class:"brand_name under-lined #{@event_name_en+"_content"}" %><br><br>
            <% brand["products"].each do |product| %>
            <%= link_to product["shopping_link"] do %>
            <div class="thumbnail" style="display: inline-block; width: 12rem; height: 20rem">
              <%= image_tag product["image_url"], :size =>'80x80'%>
              <div class="caption">
                <p class="line-3"><%= product["item_name"]%></p>
                <%= number_with_delimiter(product["price"]) %>円 <br>
                <%= tag.span product["release_at"].strftime("%Y年%m月%d日"), class:"time"%>
              </div>
            </div>
            <% end %>
            <% end %>
          </div>
          <% end %>
        </div>
      </li>
      <li class="price-list-item">
        <div class="list-head">
          <h3 class="list-name">2,000~5,000円</h3>
          <span class="list-icon <%= @event_name_en+"_content" %>">+</span>
        </div>
        <div class="answer">
          <% @lowprice.each do |brand| %>
          <div class="row">
            <%= tag.span brand["brand_name"], class:"brand_name under-lined #{@event_name_en+"_content"}" %><br><br>
            <% brand["products"].each do |product| %>
            <%= link_to product["shopping_link"] do %>
            <div class="thumbnail" style="display: inline-block; width: 12rem; height: 20rem">
              <%= image_tag product["image_url"], :size =>'80x80'%>
              <div class="caption">
                <p class="line-3"><%= product["item_name"]%></p>
                <%= number_with_delimiter(product["price"]) %>円 <br>
                <%= tag.span product["release_at"].strftime("%Y年%m月%d日"), class:"time"%>
              </div>
            </div>
            <% end %>
            <% end %>
          </div>
          <% end %>
        </div>
      </li>
      <li class="price-list-item">
        <div class="list-head">
          <h3 class="list-name">5,000~10,000円</h3>
          <span class="list-icon <%= @event_name_en+"_content" %>">+</span>
        </div>
        <div class="answer">
          <% @middleprice.each do |brand| %>
          <div class="row">
            <%= tag.span brand["brand_name"], class:"brand_name under-lined #{@event_name_en+"_content"}" %><br><br>
            <% brand["products"].each do |product| %>
            <%= link_to product["shopping_link"] do %>
            <div class="thumbnail" style="display: inline-block; width: 12rem; height: 20rem">
              <%= image_tag product["image_url"], :size =>'80x80'%>
              <div class="caption">
                <p class="line-3"><%= product["item_name"]%></p>
                <%= number_with_delimiter(product["price"]) %>円 <br>
                <%= tag.span product["release_at"].strftime("%Y年%m月%d日"), class:"time"%>
              </div>
            </div>
            <% end %>
            <% end %>
          </div>
          <% end %>
        </div>
      </li>
      <li class="price-list-item">
        <div class="list-head">
          <h3 class="list-name">10,000円以上</h3>
          <span class="list-icon <%= @event_name_en+"_content" %>">+</span>
        </div>
        <div class="answer">
          <% @highprice.each do |brand| %>
          <div class="row">
            <%= tag.span brand["brand_name"], class:"brand_name under-lined #{@event_name_en+"_content"}" %><br><br>
            <% brand["products"].each do |product| %>
            <%= link_to product["shopping_link"] do %>
            <div class="thumbnail" style="display: inline-block; width: 12rem; height: 20rem">
              <%= image_tag product["image_url"], :size =>'80x80'%>
              <div class="caption">
                <p class="line-3"><%= product["item_name"]%></p>
                <%= number_with_delimiter(product["price"]) %>円 <br>
                <%= tag.span product["release_at"].strftime("%Y年%m月%d日"), class:"time"%>
              </div>
            </div>
            <% end %>
            <% end %>
          </div>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/main/gift_rank.html.erb
<%= stylesheet_link_tag 'gift' %>
<% provide(:title, "週間ランキング") %>

<div class="col-md-9">
  <div class="price-wrapper">
    <h2><span class="under-lined">週間ランキング</span></h2>
        <% @ranking.each do |product| %>

        <%= link_to product["shopping_link"] do %>
            <div class="thumbnail" style="display: inline-block; width: 24.7%; padding: 0px;">
              <span class="ranking-num"><%= product["rank"] %></span>
              <%= image_tag product["image_url"], :size =>'135x135'%>
              <div class="caption">
                <p class="line-3"><%= product["item_name"]%></p>
                <%= number_with_delimiter(product["volume_price_label"]) %> <br>
              </div>
            </div>
        <% end %>

        <% end %>
        </div>
  </div>
</div>

app/views/main/gift_recommend.html.erb
<% provide(:title, "おすすめ") %>

<style>
  .form_title {
    background-color: white;
    margin: 10px;
    border-radius: 10px;
  }
  .form {
    background-color: lightgray;
    margin-top: 35px;
    margin-bottom: 10px;
    margin-left: 150px;
    border-radius: 10px;
  }
  .result {
    background-color: lightgray;
    color: black;
    margin-top: 20px;
    margin-bottom: 10px;
    margin-left: 150px;
    border-radius: 10px;
  }
  .no_image {
    margin-left: 5px;
  }
</style>

<div class="form_title col-md-9">
  <h1>普段使っているコスメを入力してね♪</h1>
  <h4><a href="https://www.cosme.net" target="_blank"><font color="#2EB6AA">@cosme</font></a>のデータを使って
  普段使いしているコスメからあなたにピッタリの新しいコスメをおすすめするよ♪</h4>
</div>
<div class="form col-md-2">
  <form>
    <br>
    コスメ1
    <input><br><br>
    コスメ2
    <input><br><br>
    コスメ3
    <input><br><br>
    コスメ4
    <input><br><br>
    <input type="submit" name="btng" value="コスメを見つける！" class="btn btn-info"><br><br>
  </form>
</div>

<a href=<%= gift_recommend_path %>>
  <div class="result col-md-3">
    <h4>あなたにぴったりのコスメは・・・</h4>
    <div class="no_image">
      <img src="https://www.photolibrary.jp/mhd4/img492/450-20161013225958181017.jpg" alt="no image" width="290" height="290" border="0" />
    </div>
    <h5 class="check">CHECK!</h5>
  </div>
</a>

app/views/main/index.html.erb
<%= stylesheet_link_tag 'index' %>
<% provide(:title, "トップページ") %>

<div class="event_name <%= @event_name_en+"_content" %> col-md-9">〜<%= @event_name_ja %>〜</div>

<a href=<%= gift_new_event_path(@event_name_en) %>>
  <div class="content <%= @event_name_en+"_content" %> col-md-3">
    <h1>新作コスメ</h1>
    <h5>価格別・ブランド別に</h5>
    <h5>新作コスメを探してみよう♪</h5>
    <div class="img"><%= image_tag("new_snap.jpg", :size =>'290x290', alt: "new snap") %></div>
    <h5 class="check">CHECK!</h5>
  </div>
</a>

<a href=<%= gift_rank_path %>>
  <div class="content <%= @event_name_en+"_content" %> col-md-3">
    <h1>週間ランキング</h1>
    <h5>まずはランキングを見てみたい！</h5>
    <h5>という方はこちらから♪</h5>
    <div class="img"><%= image_tag("rank_snap.jpeg", :size =>'290x290', alt: "rank snap") %></div>
    <h5 class="check">CHECK!</h5>
  </div>
</a>

<a href=<%= gift_recommend_path %>>
  <div class="content <%= @event_name_en+"_content" %> col-md-3">
    <h1>おすすめ</h1>
    <h5>普段使いしているコスメから</h5>
    <h5>新しいコスメをおすすめ♪</h5>
    <div class="img"><%= image_tag("recommend_snap.jpg", :size =>'290x290', alt: "recommend snap") %></div>
    <h5 class="check">CHECK!</h5>
  </div>
</a>